GET http://localhost:2000/hello

###

GET http://localhost:3000/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvaSIsInBhc3N3b3JkIjoic2thdGVyIiwibmFtZSI6IkJvaUtld2wiLCJlbWFpbCI6ImJvaUBrZXdsa2lkcy5jb20iLCJpYXQiOjE2ODExMTE1NDYsImV4cCI6MTY4MTExNTE0Nn0.6M9HI5Lnn1MajM0QOxIsk3ic91Eyp5xcCePSD9fWl8Q
###
GET http://localhost:3000/login 
Content-Type: application/json

{
    "user_id": "R2769",
    "password": "mudmud"
}

###
POST http://localhost:3000/registeruser
Content-Type: application/json 

{
    "user_id": "R5552",
    "password": "skrrttttt",
    "name": "boi",
    "unit": "T-11-1",
    "hp_num" : "543",
    "role" : "resident",
    "currentrole" : "admin"
}

###
POST http://localhost:3000/registervisitor
Content-Type: application/json 

{
    "ref" : "672831021",
    "name": "Megaman",
    "IC_num": "220131-07-4531",
    "car_num": "UTeM 1234",
    "hp_num" : "012-2131231",
    "pass": "VISITOR-0A",
    "category" : "VISITOR",
    "date" : "2023-06-21",
    "unit" : "T-3-1",
    "user_id" : "R0711"
}

###
GET http://localhost:3000/createQRvisitor
Content-Type: application/json 

{ 
    "IC_num": "220131-07-4531"
}

###
GET http://localhost:3000/readQRvisitor
Content-Type: application/json 

{ 
    "file": "visitorPass.png"
}

