GET http://localhost:3000/login 
Content-Type: application/json

#{
#    "user_id": "S2203",
#    "password": "stellar"
#}

# {
#    "user_id": "R2769",
#    "password": "mudmud"
# }

{
    "user_id": "A3100",
    "password": "lyla"
}

###
GET http://localhost:3000/finduser
Content-Type: application/json 
Authorization: Bearer 

{
    "user_id": "R2769"
}

###
POST http://localhost:3000/registeruser
Content-Type: application/json 
Authorization: Bearer 

{
    "user_id": "R5552",
    "password": "NoPeeking",
    "name": "NotAResident",
    "unit": "T-420-10",
    "hp_num" : "012-61945211",
    "role" : "resident"
}

###
PATCH http://localhost:3000/updateUser
Content-Type: application/json
Authorization: Bearer 

{
    "user_id": "R5552",
    "name": "boyiboyiii",
    "password" : "sheela9103i",
    "unit": "T-7-5",
    "hp_num": "0173902719"
}

###
DELETE http://localhost:3000/deleteUser
Content-Type: application/json 
Authorization: Bearer 

{
    "user_id": "R5552"
}

###
POST http://localhost:3000/registervisitor
Content-Type: application/json 
Authorization: Bearer 

{
    "ref" : "647112110",
    "name": "zenitsu",
    "IC_num": "111131-07-6121",
    "car_num": "UTeM 5555",
    "hp_num" : "012-61942211",
    "pass": "DELIVERY_0A",
    "category" : "DELIVERY",
    "date" : "2023-06-30",
    "unit" : "T-7-4"
}

###
POST http://localhost:3000/checkIn
Content-Type: application/json 
Authorization: Bearer 

{
    "log_id": "3",
    "ref" : "672831021"
}

###
PATCH http://localhost:3000/checkOut
Content-Type: application/json 
Authorization: Bearer 

{
    "log_id": "1"
}

###
GET http://localhost:3000/findvisitor
Content-Type: application/json 
Authorization: Bearer 

{
    "ref_num":"647112110"
}

###
GET http://localhost:3000/createQRvisitor
Content-Type: application/json 
Authorization: Bearer 

{ 
    "IC_num": "960417-07-0110"
}

###
PATCH http://localhost:3000/updateVisitor
Content-Type: application/json
Authorization: Bearer 

{
    "ref_num": "615671031",
    "IC_num": "891004-07-0110",
    "hp": "01109876123",
    "car_num": "WWW7777"
}

###
DELETE http://localhost:3000/deleteVisitor
Content-Type: application/json 
Authorization: Bearer 

{
    "ref_num": "615671031"
}

###
GET http://localhost:3000/findvisitorlog
Content-Type: application/json 
Authorization: Bearer 

{
    "log_id": "1"
}
