GET http://localhost:3000/login 
Content-Type: application/json

{
    "user_id": "A3100",
    "password": "lyla"
}

###
POST http://localhost:3000/registeruser
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0NjQ2NjdlMGU3M2UyMWRlNDBjNTYiLCJ1c2VyX2lkIjoiQTMxMDAiLCJwYXNzd29yZCI6Imx5bGEiLCJuYW1lIjoicm9ja2V0IiwidW5pdCI6Im1hbmFnZW1lbnQiLCJocF9udW0iOiIzMTIzMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjMyNDM2NSwiZXhwIjoxNjg2MzI3OTY1fQ.jeNUpJaajhFSJgpRkrNnZLVJTZudVKcyHxGJkZtiDS4

{
    "user_id": "R5552",
    "password": "skrrttttt",
    "name": "boi",
    "unit": "T-11-1",
    "hp_num" : "543",
    "role" : "resident"
}

###
POST http://localhost:3000/registervisitor
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0NjQ2NjdlMGU3M2UyMWRlNDBjNTYiLCJ1c2VyX2lkIjoiQTMxMDAiLCJwYXNzd29yZCI6Imx5bGEiLCJuYW1lIjoicm9ja2V0IiwidW5pdCI6Im1hbmFnZW1lbnQiLCJocF9udW0iOiIzMTIzMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjI3MzAyNSwiZXhwIjoxNjg2Mjc2NjI1fQ.Z8jrxynHp4jyl7D9woPR71GgPOo9AbGuPETHimJATnA

{
    "ref" : "672831021",
    "name": "Megaman",
    "IC_num": "220131-07-4531",
    "car_num": "UTeM 1234",
    "hp_num" : "012-2131231",
    "pass": "VISITOR-0A",
    "category" : "VISITOR",
    "date" : "2023-06-21",
    "unit" : "T-3-1",
    "user_id" : "R0711"
}

###
GET http://localhost:3000/createQRvisitor
Content-Type: application/json 

{ 
    "IC_num": "220131-07-4531"
}

###
GET http://localhost:3000/readQRvisitor
Content-Type: application/json 

{ 
    "file": "visitorPass.png"
}

###
POST http://localhost:3000/checkIn
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0NjQ2NjdlMGU3M2UyMWRlNDBjNTYiLCJ1c2VyX2lkIjoiQTMxMDAiLCJwYXNzd29yZCI6Imx5bGEiLCJuYW1lIjoicm9ja2V0IiwidW5pdCI6Im1hbmFnZW1lbnQiLCJocF9udW0iOiIzMTIzMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjMyNDM2NSwiZXhwIjoxNjg2MzI3OTY1fQ.jeNUpJaajhFSJgpRkrNnZLVJTZudVKcyHxGJkZtiDS4

{
    "log_id": "1",
    "ref" : "672831021",
    "user_id" : "S2203",
    "currentrole" : "security"
}

###
PATCH http://localhost:3000/checkOut
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0NjQ2NjdlMGU3M2UyMWRlNDBjNTYiLCJ1c2VyX2lkIjoiQTMxMDAiLCJwYXNzd29yZCI6Imx5bGEiLCJuYW1lIjoicm9ja2V0IiwidW5pdCI6Im1hbmFnZW1lbnQiLCJocF9udW0iOiIzMTIzMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjMyNDM2NSwiZXhwIjoxNjg2MzI3OTY1fQ.jeNUpJaajhFSJgpRkrNnZLVJTZudVKcyHxGJkZtiDS4

{
    "log_id": "1",
    "currentrole" : "security"
}

